
---
title: "My first Markdown"
author: "Angelos Theodorakis"
date: "16/4/2020"
output: html_document

---

This is my first Markdown Document!
 #md_document:
    #variant: markdown_github


## Let's load some libraries


```{r}
library(foreign)
library(knitr)
library(ggplot2)
library(scales)
library(dplyr)
source("http://peterhaschke.com/Code/multiplot.R")
```

### Now let's load the data

```{r}
data <- read.spss("C:/Users/User/Desktop/Άγγελος/ΕΛΚΕ/Έρευνα/sodanet/My-encoding.sav",use.value.labels = FALSE, to.data.frame=TRUE)

#or file.choose()
```

# The variable labels in a matrix (Maybe seperate file)
```{r}
dataset.labels <- as.data.frame(attr(data, "variable.labels"))
knitr::kable(dataset.labels, caption = "Labels table", floating.environment="sidewaystable")
```

# First we will find all the missing values

```{r}

Missing_values<-data.frame(sort(sapply(data,function(x) sum(is.na(x))),decreasing = TRUE))
knitr::kable(Missing_values, caption = "Missing values table", floating.environment="sidewaystable")
knitr::kable(Missing_values, format = "html", table.attr = "style='width:30%;'")
```


# Now let's try some plots



```{r}

p1<-ggplot(data, aes(x = factor(Q1))) +  
  geom_bar(aes(y = (..count..)/sum(..count..), fill = factor(Q1))) + 
  geom_text(aes( label = scales::percent((..count..)/sum(..count..)),
                 y=(..count..)/sum(..count..) ), stat= "count", vjust = -.3) +
  scale_y_continuous(labels = percent) +
  labs(title='Ποσοστό Φύλων αποφοίτων ΠΜΣ', x='Φύλο',y='Ποσοστό')+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(labels=c('Γυναίκες','Άνδρες'))+
  scale_fill_discrete(name = "Φύλο", 
                       labels=c("Γυναίκες", "Άνδρες"))


p2<-ggplot(data, aes(x = factor(Age))) +  
  geom_bar(aes(y = (..count..)/sum(..count..), fill = factor(Age))) + 
  geom_text(aes( label = scales::percent((..count..)/sum(..count..)),
                 y=(..count..)/sum(..count..) ), stat= "count", vjust = -.3) +
  scale_y_continuous(labels = percent) +
  labs(title='Ποσοστό Ηλικίας αποφοίτων ΠΜΣ', x='Ηλικία',y='Ποσοστό')+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(labels=c('25-29','30-34','35-39','40+'))+
  scale_fill_discrete(name = "Ηλικία", 
                      labels=c('25-29','30-34','35-39','40+'))

ggplot(data, aes(x = factor(Gradyear))) +  
  geom_bar(aes(y = (..count..)/sum(..count..), fill = factor(Gradyear))) + 
  geom_text(aes( label = scales::percent((..count..)/sum(..count..)),
                 y=(..count..)/sum(..count..) ), stat= "count", vjust = -.3) +
  scale_y_continuous(labels = percent) +
  labs(title='Ποσοστό Έτών Αποφοίτησης', x='Έτος αποφοίτησης',y='Ποσοστό')+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(labels=c('1997-2002','2003-2007','2008-2012','2013-2017'))+
  scale_fill_discrete(name = "Φύλο", 
                      labels=c('1997-2002','2003-2007','2008-2012','2013-2017'))

multiplot(p1, p2, cols=2)
```


## Γραφήματα που αφορούν την επιλογή των απόφοιτων για τη σύσταση του μεταπτυχιακό σε τρίτους
```{r}

ggplot(data, aes(x = factor(Q13))) +  
  geom_bar(aes(y = (..count..)/sum(..count..), fill = factor(Q13))) + 
  geom_text(aes( label = scales::percent((..count..)/sum(..count..)),
                 y=(..count..)/sum(..count..) ), stat= "count", vjust = -.3) +
  scale_y_continuous(labels = percent) + 
  labs(title='Θα συστήνατε το μεταπτυχιακό;', x='Απάντηση',y='Πλήθος',
       fill='Θα συστήνατε 
το μεταπτυχιακό?')+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(labels=c('Σίγουρα ναι','Μάλλον ναι','Ούτε ναι ούτε όχι','Μάλλον όχι','Σίγουρα όχι'))+
scale_fill_discrete(labels=c('Σίγουρα ναι','Μάλλον ναι','Ούτε ναι ούτε όχι','Μάλλον όχι','Σίγουρα όχι'))

```

```{r,fig.width=12,fig.height=8}
data$Q3Factor <- factor(data$Q3, labels = c("Πολιτική Επιστήμη και Κοινωνιολογία", "Διεθνείς και Ευρωπαϊκές σπουδές", "Κράτος και Δημόσια Πολιτική", "Σπουδές Νοτ/ης Ευρώπης"))


ggplot(data, aes(x = factor(Q13),fill=factor(Q13))) +  
  geom_bar(width=0.5) + 
  labs(title='Θα συστήνατε το μεταπτυχιακό;
(Διαχωρισμός ανα τμήμα)',
       x='Απάντηση',y='Πλήθος')+
  facet_wrap(~factor(Q3Factor))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(labels=c('Σίγουρα ναι','Μάλλον ναι','Ούτε ναι ούτε όχι','Μάλλον όχι','Σίγουρα όχι'))+
  scale_fill_discrete(name='Απάντηση',labels=c('Σίγουρα ναι','Μάλλον ναι','Ούτε ναι ούτε όχι','Μάλλον όχι','Σίγουρα όχι'))

ggplot(data, aes(x = factor(Q13),fill=factor(Q1))) +  
  geom_bar(width=0.5) + 
  labs(title='Θα συστήνατε το μεταπτυχιακό;
(Διαχωρισμός ανα τμήμα και φύλο)',
       x='Απάντηση',y='Πλήθος')+
  facet_wrap(~factor(Q3Factor))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_x_discrete(labels=c('Σίγουρα ναι','Μάλλον ναι','Ούτε ναι ούτε όχι','Μάλλον όχι','Σίγουρα όχι'))+
  scale_fill_discrete(name='Φύλο',labels=c('Γυναίκες','Άνδρες'))
```






## Ποσοστά
```{r}

round(sapply(table(as.factor(data$Emplmnt)),function(x) x/length(which(!is.na(data$Q6)))*100),1)

data.frame(attr(data$Emplmnt,"value.labels"))

```



